### ISSUE TITLE
use database replace .csv get error：nodejs.AlreadyHasActiveConnectionError

### ISSUE THREAD

**Issue by Shaun-Li** [node-casbin/egg-authz#3]
config.default.js：

```js
config.middleware = ['user','authz'];
  config.authz = {
    enable: true,
    newEnforcer: async() => {
      const dbConnect = await TypeORMAdapter.newAdapter({
        "type": "mysql",
        "host": "localhost",
        "port": 3306,
        "username": "root",
        "password": "123456",
        "database": "casbin"
      });
      const enforcer = await casbin.newEnforcer('authz_model.conf', dbConnect);
      return enforcer
    }
  }
```

use .csv is ok，but use database get error when HTTP request more than one time.
ERROR：nodejs.AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session

**Comment by nodece** [comment]
Should use single pattern :) Yan can run it and is working. 

```js
const appBoot = {
  enforcer: null,
  newCasbin: async () => {
    if(!this.enforcer){
      const dbConnect = await TypeORMAdapter.newAdapter({
        "type": "mysql",
        "host": "localhost",
        "port": 3306,
        "username": "root",
        "password": "123456",
        "database": "casbin"
      });
      this.enforcer = await casbin.newEnforcer('authz_model.conf', dbConnect);
    }
    return this.enforcer
  }
}

module.exports = {
  middleware: [ 'user', 'authz' ],
  authz: {
    enable: true,
    newEnforcer: async () => {
      const e = await appBoot.newCasbin()
      return e        
    }
  }
}
```

**Comment by nodece** [comment]
@Shaun-Li typeorm-adapter v1.0.3 has been published and fixed where this errror.

**Comment by hsluoyz** [comment]
Well, I'm happy to see it's fixed, but I just wonder why this issue is not in: https://github.com/node-casbin/typeorm-adapter ?

**Comment by thakurakhilesh** [comment]
I am using nestjs and install casbin and typeorm-adapter v1.2.0. I am facing below issue.
**Error**: **AlreadyHasActiveConnectionError: Cannot create a new connection named "node-casbin-official", because connection with such name already exist and it now has an active connection session**

Node version: 12.0.0
My  code is:
**Filename**: main.ts

import { authz } from './auth-module/authorization.middleware';
async function bootstrap(): Promise<void> {
app.use(authz(async () => {
          const adapter = await TypeORMAdapter.newAdapter(configService.getTypeOrmAdapter());
          const e = await newEnforcer('/var/www/html/avantha-audit-pro-api/src/casbin_conf/rbac_model.conf', adapter);
        // Load the policy from DB.
        await e.loadPolicy();
        return e;
    }));
}
bootstrap();

**Filename**:authorization.middleware.ts

import { Enforcer, newEnforcer } from 'casbin';
import TypeORMAdapter from 'typeorm-adapter';


export class BasicAuthorizer {
  private req: any;
  private enforcer: any;

  constructor(req, enforcer) {
    this.req = req;
    this.enforcer = enforcer;
  }

  getUserRole() {
    const { user } = this.req;
    if(typeof user !== 'undefined'){
      const { role } = user;
      return role;
    }
    return true;

  }

  checkPermission() {
    const { req, enforcer } = this;
    const { originalUrl: path, method } = req;
    const userRole = this.getUserRole();
    if (userRole){
      return enforcer.enforce(userRole, path, method);
    }
    return true;
  }
}

// the authorizer middleware
export function authz(newEnforcer: () => Promise<Enforcer>) {
  return async (req, res, next) => {
    const enforcer = await newEnforcer();

    // user sample
    //req.user = { role: 'admin' };

    if (!(enforcer instanceof Enforcer)) {
      res.status(500).json({ 500: 'Invalid enforcer' });
      return;
    }

    const authorizer = new BasicAuthorizer(req, enforcer);
    if (!authorizer.checkPermission()) {
      res.status(403).json({ 403: 'Forbidden' });
      return;
    }

    next();
  }
};

Please help me to solve this issue.
